apiVersion: v1
kind: Service
metadata:
  name: {{ include "wildfly.fullname" . }}
spec:
  type: {{ .Values.wildfly.service.type }}
  ports:
    - port: {{ .Values.wildfly.service.port }}
      targetPort: 8080
  selector:
    app: {{ include "wildfly.name" . }}
