# vm.yml
groups:
- name: cpu-usage-alerts
  rules:
  - alert: HighCPUUsageCritical
    expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 90
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High CPU usage detected on {{`{{ $labels.instance }}`}}"
      description: "CPU usage on instance {{`{{ $labels.instance }}`}} has exceeded 90% for more than 5 minutes."
  - alert: HighCPUUsageWarning
    expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected on {{`{{ $labels.instance }}`}}"
      description: "CPU usage on instance {{`{{ $labels.instance }}`}} has exceeded 80% for more than 5 minutes."
