apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.fullname" . }}
spec:
  type: {{ .Values.mariadb.service.type }}
  ports:
    - port: {{ .Values.mariadb.service.port }}
      targetPort: 3306
  selector:
    app: {{ include "mariadb.name" . }}
