apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    {{- $prometheusTpl := .Files.Get "config/prometheus/prometheus.yml.tpl" }}
    {{- tpl $prometheusTpl . | indent 2 }}