apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.namespace }}-alertmanager-config
data:
  alertmanager.yml: |
    {{- $tpl := .Files.Get "config/alertmanager/config/alertmanager.yml" }}
    {{- tpl $tpl . | indent 4 }}
