wildfly:
  replicaCount: 1
  image:
    repository: jboss/wildfly
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080

mariadb:
  image:
    repository: mariadb
    tag: "latest"
  rootPassword: my-secret-pw
  db: mydatabase
  service:
    type: ClusterIP
    port: 3306
