# alertmanager.yml

# 基本配置
global:
  resolve_timeout: 5m # 解析告警超时时间

time_intervals:
- name: workdays
  time_intervals:
  - weekdays: ['monday:friday']
    times:
    - start_time: '09:00'
      end_time: '18:00'


# 告警分组配置
route:
  receiver: 'workhours-receiver'
  group_by: ['alertname']
  routes:
  - matchers:
    - alertname = "YourAlertName"
    receiver: 'workhours-receiver'
    active_time_intervals:
    - workdays

# 通知接收器
receivers:
- name: 'email-alerts'
  email_configs:
  - to: 'your-email@example.com'
    from: 'alertmanager@example.com'
    smarthost: 'smtp.example.com:587'
    auth_username: 'your-username'
    auth_password: 'your-password'
    auth_identity: 'your-username'
    require_tls: true

- name: 'slack-alerts'
  slack_configs:
  - channel: '#alerts'
    api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'
    send_resolved: true

- name: 'default-receiver'
  email_configs:
  - to: 'default@example.com'
    send_resolved: true
