# alertmanager.yml

# 基本配置
global:
  resolve_timeout: 5m # 解析告警超时时间

# 通知接收器
receivers:
- name: 'email-alerts'
  email_configs:
  - to: 'your-email@example.com'
    from: 'alertmanager@example.com'
    smarthost: 'smtp.example.com:587'
    auth_username: 'your-username'
    auth_password: 'your-password'
    auth_identity: 'your-username'
    require_tls: true

- name: 'slack-alerts'
  slack_configs:
  - channel: '#alerts'
    api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'
    send_resolved: true

# 告警分组配置
route:
  receiver: 'email-alerts'
  group_by: ['alertname', 'priority']
  group_wait: 30s # 在分组之前等待的时间
  group_interval: 5m # 分组后等待的时间
  repeat_interval: 12h # 重复告警的间隔

# 抑制配置
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'namespace']

# 其他全局配置
receivers:
- name: 'default-receiver'
  email_configs:
  - to: 'default@example.com'
    send_resolved: true
